# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

#Using ubuntu
  config.vm.box = "ubuntu/trusty64"

# hostname and IP configuration
  config.vm.hostname = "web"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "10.0.0.10"
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
   SHELL

# Adding chef_zero provisioner
  config.vm.provision "chef_zero" do |chef|
    chef.cookbooks_path = "#{File.dirname(__FILE__)}/../../configuration"
   # Adding recipes
    chef.add_recipe "role-web-nginx"
  end
end
